### PR TITLE
Merge upstream/main into Feature Branch

### PR DESCRIPTION
**Pull request by timothyas**
This will fix JAX problems, and using an updated JAX version seems to be ~7% faster.

### CODE REVIEW

**Comment by timothyas** [comment]
@danielabdi-noaa this will update the graphcast feature branch that we use in our repo. It fixes the JAX issues that we were running into, and seems a bit faster. If you agree I'll go ahead and merge, then I'll open a PR on our private repo that updates the submodules there.

**Comment by timothyas** [comment]
I'll go ahead and "regular" merge this instead of squash merge so we get a clear timeline for when things work.

**Comment by danielabdi-noaa** [comment]
@timothyas Looks good to me. I am curious about the issue that is preventing us from using the "main" branch?

**Comment by timothyas** [comment]
Thanks @danielabdi-noaa. We could use the main branch, but I think it is safer to let the main branch track upstream/main directly, and then have a separate feature branch that has our own features on it.

**Pull request merged**
